name: CI/CD Pipeline with Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test

  build-and-push-to-dockerhub:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t devops-poc-app .
    
    - name: Test Docker container
      run: |
        docker run -d -p 3000:3000 --name test-app devops-poc-app
        sleep 5
        curl -f http://localhost:3000/health
        docker stop test-app
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker tag devops-poc-app ${{ secrets.DOCKERHUB_USERNAME }}/devops-poc:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-poc:latest
        echo "Image pushed to Docker Hub: ${{ secrets.DOCKERHUB_USERNAME }}/devops-poc:latest"